# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emily Cutler
email: parsnipc@yahoo.com.au
description: > # this means to ignore newlines until "baseurl:"
  Emily Cutler - UI/UX Designer and Front End Developer
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://parsnipc.github.io" # the base hostname & protocol for your site
twitter_username: parsnipc
github_username:  parsnipc

# Build settings
markdown: kramdown